#!/bin/bash
INSTALLPATH='/home/zenaiev/games/Diablo2/502/lootfilter/D2-Maphack-for-Linux/build'
open=`ps -e | grep Game.exe | wc -l`
if [ $open -gt 0 ]; then
	pid=`ps -e | grep -m 1 Game.exe | sed -e 's/^ *//' -e 's/^\([0-9][0-9]*\) .*/\1/'`
	#sudo surgeon -i $pid /usr/local/lib/snoogans.so
	sudo $INSTALLPATH/surgeon -i $pid $INSTALLPATH/snoogans.so
else
	echo "err: couldn't find Game.exe"
fi

